---

- name: test dir
  command: ls -ald /etc/apt/apt.conf.d

- name: test dir contents
  command: ls -al /etc/apt/apt.conf.d/

- name: test copy
  command: cp /etc/passwd /etc/apt/apt.conf.d/passwd
  become: true

- name: ensure recommends are never installed
  copy:
    src: 99recommends
    dest: /etc/apt/apt.conf.d/99recommends
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  become_method: sudo

- name: ensure apt cleans up after itself
  copy:
    src: 99clean
    dest: /etc/apt/apt.conf.d/99clean
    owner: root
    group: root
    mode: 0644

- name: do not install different languages
  copy:
    src: 99languages
    dest: /etc/apt/apt.conf.d/99languages
    owner: root
    group: root
    mode: 0644

- name: do not start daemons after install
  copy:
    src: policy-rc.d
    dest: /usr/sbin/policy-rc.d
    owner: root
    group: root
    mode: 0755

- name: apt update and dist-upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: disable unwanted services
  systemd:
    name: "{{ item }}"
    enable: no
    mask: yes
  with_items:
    - accounts-daemon
    - iscsi
    - iscsid
    - lvm2-monitor
    - lxcfs
