---

- name: copy deb from s3
  command: "aws s3 cp s3://agy-deb/{{ consul_package }} /tmp/{{ consul_package }}"

- name: install consul
  command: "dpkg --install /tmp/{{ consul_package }}"
  become: true
