---

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  become: true

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    update_cache: yes
  become: true

- name: install docker-engine
  apt:
    name: docker-ce=17.09.0~ce-0~ubuntu
  become: true
