---

- name: copy deb from s3
  command: "aws s3 cp s3://agy-deb/{{ go_audit_package }} /tmp/{{ go_audit_package }}"

- name: install go-audit
  command: "dpkg --install /tmp/{{ go_audit_package }}"
  become: true
