---

- name: disable unwanted services
  systemd:
    name: "{{ item }}"
    enabled: no
  with_items:
    - accounts-daemon
    - iscsi
    - iscsid
    - lvm2-lvmetad
    - lvm2-monitor
    - lxcfs
    - snapd
  become: true

- include: apt.yml
- include: kernel.yml
- include: hostname.yml
- include: docker.yml
